apiVersion: batch/v1
kind: Job
metadata:
  name: backup-job
  namespace: demo
spec:
  template:
    spec:
      containers:
      - name: pi
        image: pritam99/backup:v1
      restartPolicy: Never
  backoffLimit: 1