# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: backup
# provisioner: rancher.io/local-path
# reclaimPolicy: Retain
# volumeBindingMode: WaitForFirstConsumer

# ---

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: backup-pv
# spec:
#   capacity:
#     storage: 5Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: linode-block-storage
#   hostPath:
#     path: /data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pvc
  namespace: demo
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem

